## WebServer

server:
  servlet:
    context-path: /api 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

## Datasource

spring:
  h2: 
    console:
      enabled: true
  datasource:
    url:  jdbc:h2:mem:testdb
    driveClassName:  org.h2.Driver
    username: root 
    password: root 
  devstools:
    restart:
      enabled: true
  jpa:
    database-platform:  
